### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by kuuak** [superhuit-agency/starterpack-i18n#1]
```
PHP Fatal error:  Uncaught Error: Call to undefined function SUPT\\StarterpackI18n\\get_localized_post_id() in /var/www/html/wp-content/plugins/vidy-content-structure/includes/Taxonomies/SeasonTaxonomy.php:177
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(305): SUPT\\VidyContentStructure\\Taxonomies\\SeasonTaxonomy->term_link('/category/uncat...', Object(WP_Term))
#1 /var/www/html/wp-includes/plugin.php(189): WP_Hook->apply_filters('/category/uncat...', Array)
#2 /var/www/html/wp-includes/taxonomy.php(4559): apply_filters('term_link', 'http://localhos...', Object(WP_Term), 'category')
#3 /var/www/html/wp-content/plugins/nextjs-revalidate/include/Cron/PurgeAll.php(36): get_term_link(Object(WP_Term))
#4 /var/www/html/wp-includes/class-wp-hook.php(303): NextJsRevalidate\\Cron\\PurgeAll->run_cron_hook()
#5 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#6 /var/www/html/wp-includes/plugin.php(518): WP_Hook->do_action(Array)
#7 /var/www/html/wp-cron.php(138): do_action_ref_array('nextjs-re in /var/www/html/wp-content/plugins/vidy-content-structure/includes/Taxonomies/SeasonTaxonomy.php on line 177, referer: http://localhost/wp-cron.php?doing_wp_cron=1684133841.9365329742431640625000
```

**Comment by kuuak** [comment]
The plugin wasn't correctly installed 🙈
